### PR TITLE
Fixed adding of zeroclipboard-is-hover class to className in IE9

### PR DESCRIPTION
**Pull request by heyitsmark**
For some reason, `element.hasOwnProperty("className")` returns `false` in IE9, which results in zeroclipboard-is-hover class not being added to className.  This means the hover effect is not displayed. This commit uses an alternative way of checking for this property's existence to fix this issue.

Sadly flex-sdk install failed, so I was unable to run the test cases, but that should be easy to verify in an environment where flex-sdk is working.

I manually tested the functionality successfully in IE9, IE10 on Win7; Chrome 39, Firefox 34, Safari on OSX Mavericks.

### CODE REVIEW

**Comment by JamesMGreene** [comment]
> For some reason, `element.hasOwnProperty("className")` returns `false` in IE9, which results in zeroclipboard-is-hover class not being added to className.

Huh, well that's special.  I suppose that's when they introduced `HTMLDivElement.prototype` ==`HTMLElement`, `HTMLElement.prototype` == `Element`, etc. or something like that.

Thanks for the catch!

I should probably just do a full review of our `_addClass`/`_removeClass`/`_hasClass` methods and compare them to something rock solid like jQuery's implementations (minus the jQuery-specific bits, of course): [jquery/jquery@src/attributes/classes.js](https://github.com/jquery/jquery/blob/53aa87f3bf4284763405f3eb8affff296e55ba4f/src/attributes/classes.js)

**Comment by JamesMGreene** [comment]
P.S. This probably fixes #501.

**Comment by kensnyder** [comment]
Also note that `element.hasOwnProperty("className")` also returns `false` in Firefox (as of 36). Because FF supports classList, it doesn't matter in this case, but I just thought I'd mention it.

**Comment by JamesMGreene** [comment]
Merged. Thanks!

**Pull request closed without merging**
